In [83]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
import numpy as np
import math

In [84]:
corpus = [
    'the sun is a star',
    'the moon is a satellite',
    'the sun and moon are celestial bodies'
]

Manual CountVectorizer

In [89]:
word_count = {}
word_index = []
for line in corpus:
    for word in line.split(" "):
        if word in word_count:
            word_count[word] += 1
        else:
            word_index.append(word)
            word_count[word] = 1
final_transformed = np.zeros((len(corpus),len(word_count)))
for i in range(len(corpus)):
    for word in corpus[i].split(" "):
        final_transformed[i][word_index.index(word)] += 1
print(final_transformed)
count_vect = CountVectorizer()
count_vect.fit(corpus)
X = count_vect.transform(corpus)
print(X.toarray())

[[1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 1. 0. 1. 1. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0. 1. 0. 1. 1. 1. 1.]]
[[0 0 0 0 1 0 0 1 1 1]
 [0 0 0 0 1 1 1 0 0 1]
 [1 1 1 1 0 1 0 0 1 1]]


Manual TfIdfVectorizer

In [90]:
len_corpus = len(corpus)
word_index = []
for line in corpus:
    for word in line.split(" "):
        if word not in word_index:
            word_index.append(word)
        index = word_index.index(word)
len_word_index = len(word_index)
document_appearances = np.zeros(len_word_index)
for i in range(len_word_index):
    word = word_index[i]
    for j in range(len_corpus):
        if word in corpus[j]:
            document_appearances[i] += 1
for i in range(len(document_appearances)):
    document_appearances[i] = 1 + (math.log((len_corpus + 1) / (document_appearances[i] + 1)))
final_transformed = np.zeros((len_corpus,len_word_index))
for i in range(len_corpus):
    temp_list = corpus[i].split(" ")
    len_temp_list = len(temp_list)
    for word in temp_list:
        final_transformed[i][word_index.index(word)] += 1
    for word in temp_list:
        index = word_index.index(word)
        final_transformed[i][index] = final_transformed[i][index] * document_appearances[index]
    final_transformed[i] = final_transformed[i] / np.sqrt(np.sum(final_transformed[i]**2))
print(final_transformed)
tfidf_vect = TfidfVectorizer()
tfidf_vect.fit(corpus)
X = tfidf_vect.transform(corpus)
print(X.toarray())

[[0.34957775 0.45014501 0.45014501 0.34957775 0.59188659 0.
  0.         0.         0.         0.         0.        ]
 [0.34957775 0.         0.45014501 0.34957775 0.         0.45014501
  0.59188659 0.         0.         0.         0.        ]
 [0.25171084 0.32412354 0.         0.         0.         0.32412354
  0.         0.4261835  0.4261835  0.4261835  0.4261835 ]]
[[0.         0.         0.         0.         0.4804584  0.
  0.         0.63174505 0.4804584  0.37311881]
 [0.         0.         0.         0.         0.4804584  0.4804584
  0.63174505 0.         0.         0.37311881]
 [0.4261835  0.4261835  0.4261835  0.4261835  0.         0.32412354
  0.         0.         0.32412354 0.25171084]]
