In [10]:
import numpy as np
import pandas as pd
import random

### Q1

In [37]:
def numpy_boundary_traversal(matrix):
    rows, columns = matrix.shape
    returning_array = np.zeros(2*rows+2*columns-4)
    counter = 0
    for i in range(columns):
        returning_array[counter] = matrix[0][i]
        counter += 1
    for i in range(rows - 1):
        returning_array[counter] = matrix[i + 1][columns - 1]
        counter += 1
    for i in reversed(range(columns - 1)):
        returning_array[counter] = matrix[rows - 1][i]
        counter += 1
    for i in reversed(range(rows - 2)):
        returning_array[counter] = matrix[i + 1][0]
        counter += 1
    return returning_array

In [38]:
row_size = 5
column_size = 4
a = np.random.randint(1, 51, (row_size, column_size))
print(a)
num = min(row_size, column_size)
anti_diagonal = np.zeros(num)
for i in range(num):
    anti_diagonal[i] = a[i, column_size - i - 1]
print(anti_diagonal)
for i in range(row_size):
    print(f"The max of row {i+1} is: {np.max(a[i])}")
b = a[~(a > np.mean(a))]
print(b)
print(numpy_boundary_traversal(a))

[[37  8 27 40]
 [49 33 46  9]
 [22  2 35  1]
 [22 31 46 25]
 [ 6 16 24 46]]
[40. 46.  2. 22.]
The max of row 1 is: 40
The max of row 2 is: 49
The max of row 3 is: 35
The max of row 4 is: 46
The max of row 5 is: 46
[ 8  9 22  2  1 22 25  6 16 24]
[37.  8. 27. 40.  9.  1. 25. 46. 24. 16.  6. 22. 22. 49.]


### Q2

In [78]:
def numpy_alternate_sort(matrix):
    new_matrix = np.zeros(matrix.size)
    for i in range(matrix.size):
        if i % 2:
            to_delete = np.argmin(matrix)
            new_matrix[i] = matrix[to_delete]
            matrix = np.delete(matrix, to_delete)
        else:
            to_delete = np.argmax(matrix)
            new_matrix[i] = matrix[to_delete]
            matrix = np.delete(matrix, to_delete)
    return new_matrix

In [82]:
a = np.round(np.random.rand(20) * 10, decimals=2)
print(a)
print(min(a), max(a), np.median(a))
a[np.where(a < 5)] = np.round(a[np.where(a < 5)] ** 2, 2)
print(a)
print(numpy_alternate_sort(a))

[7.59 4.73 4.62 8.16 4.36 7.64 5.15 3.17 6.68 1.38 6.98 8.67 9.08 1.23
 5.73 9.46 1.32 0.34 9.55 1.56]
0.34 9.55 5.44
[ 7.59 22.37 21.34  8.16 19.01  7.64  5.15 10.05  6.68  1.9   6.98  8.67
  9.08  1.51  5.73  9.46  1.74  0.12  9.55  2.43]
[22.37  0.12 21.34  1.51 19.01  1.74 10.05  1.9   9.55  2.43  9.46  5.15
  9.08  5.73  8.67  6.68  8.16  6.98  7.64  7.59]


### Q3

In [117]:
def pandas_filter_pass(df):
    new_df = df.loc[(df["Grade"] == "A") | (df["Grade"] == "B")]
    return new_df

In [119]:
subjects_choose = ["Mathematics", "Physics", "Chemistry"]
subjects = []
for i in range(10):
    subjects.append(random.choice(subjects_choose))
names = ["Liam", "Olivia", "Ethan", "Ava", "Noah", "Isabella", "Mason", "Sophia", "Lucas", "Mia"]
grades = []
for i in range(10):
    grades.append("")
columns = ["Name", "Subjects", "Score", "Grade"]
data = {"Name": [], "Subject": [], "Score": [], "Grade": []}
data["Name"] = names
data["Subject"] = subjects
data["Score"] = np.random.randint(50, 101, 10).tolist()
data["Grade"] = grades
df = pd.DataFrame(data)
df.loc[df["Score"] >= 90, "Grade"] = "A"
df.loc[(df["Score"] >= 80) & (df["Score"] < 90), "Grade"] = "B"
df.loc[(df["Score"] >= 70) & (df["Score"] < 80), "Grade"] = "C"
df.loc[(df["Score"] >= 60) & (df["Score"] < 70), "Grade"] = "D"
df.loc[df["Score"] < 60, "Grade"] = "F"
df.sort_values("Score", ascending=False)
print(df)
print(df.groupby(["Subject"]).mean("Score"))
print(pandas_filter_pass(df))

       Name      Subject  Score Grade
0      Liam      Physics     82     B
1    Olivia    Chemistry     66     D
2     Ethan      Physics     86     B
3       Ava      Physics     58     F
4      Noah      Physics     64     D
5  Isabella      Physics     96     A
6     Mason    Chemistry     57     F
7    Sophia      Physics     56     F
8     Lucas  Mathematics     84     B
9       Mia      Physics     61     D
                 Score
Subject               
Chemistry    61.500000
Mathematics  84.000000
Physics      71.857143
       Name      Subject  Score Grade
0      Liam      Physics     82     B
2     Ethan      Physics     86     B
5  Isabella      Physics     96     A
8     Lucas  Mathematics     84     B


In [105]:
def predict_review_sentiment(model, vectorizer, review):
    transformed_review = vectorizer.transform(review)
    return "Positive" if model.predict(transformed_review) == 1 else "Negative"

In [2]:
reviews = [
    # Positive reviews
    "Absolutely loved it! A masterpiece.",
    "Fantastic direction and great acting.",
    "Beautifully shot and emotionally powerful.",
    "One of the best films I’ve seen this year.",
    "Amazing storyline and characters.",
    "Brilliant performances from the entire cast.",
    "A truly inspiring experience.",
    "Heartwarming and unforgettable.",
    "Gripping from start to finish.",
    "A visual and emotional treat.",
    "Cinematography was top-notch.",
    "A delightful surprise, really enjoyed it.",
    "Superb in every aspect.",
    "The plot kept me hooked throughout.",
    "An exceptional movie. Highly recommended.",
    "Outstanding direction and storytelling.",
    "Incredible pacing and character depth.",
    "An emotional rollercoaster done right.",
    "So touching and meaningful.",
    "Absolutely perfect in every way.",
    "Genuinely entertaining and moving.",
    "Loved the writing and performances.",
    "A cinematic gem.",
    "Fantastic score and visuals.",
    "Emotionally rich and artistically bold.",
    "Left me speechless. Beautiful.",
    "Great chemistry among actors.",
    "A perfect blend of drama and humor.",
    "Loved every minute of it.",
    "A movie to remember.",
    "Pure magic on screen.",
    "Such a refreshing take.",
    "Emotionally satisfying and rewarding.",
    "Engaging, thoughtful, and well-paced.",
    "A deeply impactful experience.",
    "Beautiful storytelling, great cast.",
    "It hit all the right notes.",
    "Visually stunning, emotionally profound.",
    "A work of art.",
    "A powerful message delivered well.",
    "Stunning performances, great direction.",
    "Simply brilliant.",
    "An unforgettable experience.",
    "Gave me chills. So well done.",
    "Thought-provoking and well-acted.",
    "A deeply moving story.",
    "Excellent pacing and character arcs.",
    "Smart, stylish, and satisfying.",
    "Loved the emotional depth.",
    "A modern classic.",
    
    # Negative reviews
    "Terribly boring and slow.",
    "A complete waste of time.",
    "Poorly acted and badly written.",
    "I couldn’t even finish it.",
    "Predictable and uninspired.",
    "Dull plot and weak characters.",
    "Awful pacing and editing.",
    "So bad it was almost funny.",
    "Cringe-worthy dialogue throughout.",
    "Visually bland and forgettable.",
    "The story went nowhere.",
    "Not worth the hype.",
    "I wanted to like it, but couldn’t.",
    "Felt like a low-budget mess.",
    "Characters lacked depth and motivation.",
    "One of the worst I’ve seen.",
    "Too long and painfully slow.",
    "Acting was wooden and unnatural.",
    "Overly dramatic and underwhelming.",
    "An incoherent mess.",
    "It dragged on forever.",
    "Couldn’t connect with the story.",
    "Felt like it had no direction.",
    "A shallow and pointless movie.",
    "Didn’t make any emotional impact.",
    "Everything felt forced.",
    "Disappointing and forgettable.",
    "Bad writing ruined it.",
    "Just a generic, cliché film.",
    "Predictable from start to finish.",
    "Too much style, no substance.",
    "Terrible dialogue and weak plot.",
    "Unoriginal and boring.",
    "No emotional weight whatsoever.",
    "The acting was laughably bad.",
    "Completely overrated.",
    "Lacked tension and suspense.",
    "A total snoozefest.",
    "Nothing stood out.",
    "I regret watching it.",
    "Poor direction and execution.",
    "Just didn’t work.",
    "I kept checking the time.",
    "So unengaging and dull.",
    "Left no impression.",
    "It felt half-baked.",
    "A missed opportunity.",
    "Not even worth streaming.",
    "Simply awful.",
    "Don’t bother with this one."
]

In [144]:
import nltk
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.linear_model import LogisticRegression

### Q4

In [130]:
temp_dict = {"Review": reviews.copy(), "Sentiment": []}
temp_list = ["Positive"] * 50 + ["Negative"] * 50
temp_dict["Sentiment"] = temp_list.copy()
reviews_df = pd.DataFrame(temp_dict)

In [134]:
stop_words = stopwords.words('english')
count_vect = CountVectorizer(stop_words=stop_words, max_features=500)
count_vect.fit(reviews_df["Review"])
# print(count_vect.transform(["Loved"]).toarray())
X = count_vect.transform(reviews_df["Review"])
y = [1 if sentiment == "Positive" else 0 for sentiment in reviews_df["Sentiment"]]
X_train, X_test, reviews_train, reviews_test, sentiments_train, sentiments_test, y_train, y_test = train_test_split(X, reviews_df["Review"], reviews_df["Sentiment"], y, train_size=0.8, random_state=5)
MNB = MultinomialNB()
MNB.fit(X_train, y_train)
y_pred = MNB.predict(X_test)
print(accuracy_score(y_test, y_pred))
# for i in range(len(reviews_test)):
#     print(reviews_test.iloc[i])
#     print(predict_review_sentiment(MNB, count_vect, [reviews_test.iloc[i]]), sentiments_test.iloc[i])

0.9


### Q5

In [181]:
def text_preprocess_vectorize(texts, vectorizer):
    return vectorizer.transform(texts)

In [153]:
temp_dict = {"Feedback": reviews.copy(), "Label": []}
temp_list = ["Good"] * 50 + ["Bad"] * 50
temp_dict["Label"] = temp_list.copy()
feedbacks_df = pd.DataFrame(temp_dict)

In [190]:
tfidf_vect = TfidfVectorizer(lowercase=True, stop_words=stop_words, max_features=300)
tfidf_vect.fit(feedbacks_df["Feedback"])
X = tfidf_vect.transform(feedbacks_df["Feedback"])
y = [1 if label == "Good" else 0 for label in feedbacks_df["Label"]]
X_train, X_test, feedbacks_train, feedbacks_test, labels_train, labels_test, y_train, y_test = train_test_split(X, feedbacks_df["Feedback"], feedbacks_df["Label"], y, train_size=0.75, random_state=46)
LR = LogisticRegression()
LR.fit(X_train, y_train)
y_pred = LR.predict(X_test)
print(precision_score(y_test, y_pred), recall_score(y_test, y_pred), f1_score(y_test, y_pred))

0.8333333333333334 0.7692307692307693 0.8
